package com.pao.project.connection.talkUI.panel;

import com.pao.project.connection.talkUI.Message;

import javax.swing.*;
import java.awt.*;

public class MessPanel implements ListCellRenderer<Message> {
    private JPanel mainPanel;
    private JLabel userLabel;
    private JLabel messageLabel;

    public MessPanel() {
        mainPanel.setSize(480, 100);
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends Message> jList, Message message, int i, boolean b, boolean b1) {
        if (message.isMyMessage()) {
            userLabel.setHorizontalAlignment(SwingConstants.RIGHT);
            messageLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        } else {
            userLabel.setHorizontalAlignment(SwingConstants.LEFT);
            messageLabel.setHorizontalAlignment(SwingConstants.LEFT);
        }

        userLabel.setText(message.getUser());
        messageLabel.setText(message.getMessage());

        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 5, 5, 5), -1, -1));
        mainPanel.setBackground(new Color(-1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-856709));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        userLabel = new JLabel();
        userLabel.setBackground(new Color(-856709));
        Font userLabelFont = this.$$$getFont$$$(null, -1, 18, userLabel.getFont());
        if (userLabelFont != null) userLabel.setFont(userLabelFont);
        userLabel.setText("Label");
        panel1.add(userLabel, BorderLayout.NORTH);
        messageLabel = new JLabel();
        messageLabel.setBackground(new Color(-856709));
        messageLabel.setText("Label");
        panel1.add(messageLabel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
